   Pruebas    unitarias      Ramas             Director   Director.   Directo  pull_      Ramas       Director     Director traba   Prueb  Run-on   Ubuntu-última Ubuntu-últ   pasos  acciones/checkout@v3 acciones/checkout@v3  -nombreEjecutar pruebas unitarias nameEjecutar pruebas unitarias                     : 
   Nombre : Pruebas

en: Empuje

trabajos:
 CI :
 Run-on : Ubuntu-última
  pasos :
 - nombre: "Mira el repositorio"
  usos : acciones/checkout@v3
 Con :
 submódulos. : recursivo.

 - nombre: "Instalar fundición"
  usos : fundición-rs/fundería-cocina@v1
 Con :
  versión : Nocturno

 - nombre: "Ejecutar pruebas de fundición"
 Correr : Prueba de forja -vvv.
